include: package:flutter_lints/flutter.yaml

# Enforce trailing commas for function calls and declarations:
linter:
  rules:
    require_trailing_commas: true

# Optionally, enable the rule for lists, maps, and sets:
dart_code_metrics:
  metrics:
    prefer-trailing-comma: true
